name: PRM
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2019.1.23=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.3.9=py36_0
  - cffi=1.12.3=py36h2e261b9_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.3=199
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - mkl=2019.3=199
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.16.3=py36h7e9f1db_0
  - numpy-base=1.16.3=py36hde5b4d6_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1b=h7b6447c_1
  - pcre=8.43=he6710b0_0
  - pip=19.0.3=py36_0
  - pixman=0.38.0=h7b6447c_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pycparser=2.19=py36_0
  - python=3.6.8=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.0=py36_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - cuda90=1.0=h6433d27_0
  - pytorch=0.4.1=py36_py35_py27__9.0.176_7.1.2_2
  - pip:
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.0
    - chardet==3.0.4
    - cupy==5.4.0
    - cycler==0.10.0
    - cython==0.29.7
    - decorator==4.4.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - fastrlock==0.4
    - idna==2.8
    - imageio==2.5.0
    - ipykernel==5.1.0
    - ipython==7.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.3
    - jinja2==2.10.1
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-client==5.2.4
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.0.3
    - mistune==0.8.4
    - nbconvert==5.5.0
    - nbformat==4.4.0
    - nest==0.1.1
    - networkx==2.3
    - notebook==5.7.8
    - pandocfilters==1.4.2
    - parso==0.4.0
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==6.0.0
    - progress==1.5
    - prometheus-client==0.6.0
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - pycocotools==2.0
    - pygments==2.3.1
    - pyinn==0.0.1
    - pyparsing==2.4.0
    - pyrsistent==0.15.1
    - python-dateutil==2.8.0
    - pywavelets==1.0.3
    - pyyaml==3.13
    - pyzmq==18.0.1
    - qtconsole==4.4.3
    - requests==2.21.0
    - scikit-image==0.15.0
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - send2trash==1.5.0
    - shapely==1.6.4.post2
    - six==1.12.0
    - sklearn==0.0
    - terminado==0.8.2
    - testpath==0.4.2
    - torch==0.4.1.post2
    - torchfile==0.1.0
    - torchvision==0.2.2.post3
    - tornado==6.0.2
    - tqdm==4.31.1
    - traitlets==4.3.2
    - urllib3==1.24.2
    - visdom==0.1.8.8
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - websocket-client==0.56.0
    - widgetsnbextension==3.4.2
prefix: /home/ubuntu/miniconda2/envs/PRM

